title: Santhosh's DataStage Notes
author: Santhosh Gujjula
email: santhosh.gujjula430@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'll be posting my DataStage notes here.

# social links
github_username:  https://github.com/SanthoshGujjula

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
